//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PickAndPlace.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DA7667501")]
        public string CamSn {
            get {
                return ((string)(this["CamSn"]));
            }
            set {
                this["CamSn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50000")]
        public int CamExposure {
            get {
                return ((int)(this["CamExposure"]));
            }
            set {
                this["CamExposure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.5")]
        public string RobotIp {
            get {
                return ((string)(this["RobotIp"]));
            }
            set {
                this["RobotIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RobotPort {
            get {
                return ((int)(this["RobotPort"]));
            }
            set {
                this["RobotPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveEnable {
            get {
                return ((bool)(this["SaveEnable"]));
            }
            set {
                this["SaveEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SaveMode {
            get {
                return ((int)(this["SaveMode"]));
            }
            set {
                this["SaveMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SavePath {
            get {
                return ((string)(this["SavePath"]));
            }
            set {
                this["SavePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("check_service_status")]
        public string EndPointCheckStatus {
            get {
                return ((string)(this["EndPointCheckStatus"]));
            }
            set {
                this["EndPointCheckStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8386/ai")]
        public string ApiUrlAi {
            get {
                return ((string)(this["ApiUrlAi"]));
            }
            set {
                this["ApiUrlAi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("calib_2d")]
        public string EndPointCalib2d {
            get {
                return ((string)(this["EndPointCalib2d"]));
            }
            set {
                this["EndPointCalib2d"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("transform_pixel_to_robot")]
        public string EndPointTransform {
            get {
                return ((string)(this["EndPointTransform"]));
            }
            set {
                this["EndPointTransform"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("save_calib_matrix")]
        public string EndPointSaveMatrix {
            get {
                return ((string)(this["EndPointSaveMatrix"]));
            }
            set {
                this["EndPointSaveMatrix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("load_calib_matrix")]
        public string EndPointLoadMatrix {
            get {
                return ((string)(this["EndPointLoadMatrix"]));
            }
            set {
                this["EndPointLoadMatrix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("check_calib_ready_status")]
        public string EndPointCheckCalibReady {
            get {
                return ((string)(this["EndPointCheckCalibReady"]));
            }
            set {
                this["EndPointCheckCalibReady"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cal_robot_coord")]
        public string EndPointGetRealCoord {
            get {
                return ((string)(this["EndPointGetRealCoord"]));
            }
            set {
                this["EndPointGetRealCoord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StartShiftTime {
            get {
                return ((string)(this["StartShiftTime"]));
            }
            set {
                this["StartShiftTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentOK {
            get {
                return ((int)(this["CurrentOK"]));
            }
            set {
                this["CurrentOK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentNG {
            get {
                return ((int)(this["CurrentNG"]));
            }
            set {
                this["CurrentNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\BroSight\\\\Models")]
        public string MODELS_PATH {
            get {
                return ((string)(this["MODELS_PATH"]));
            }
            set {
                this["MODELS_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("load_templates")]
        public string EndPointLoadTemplates {
            get {
                return ((string)(this["EndPointLoadTemplates"]));
            }
            set {
                this["EndPointLoadTemplates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int WriteTimeout {
            get {
                return ((int)(this["WriteTimeout"]));
            }
            set {
                this["WriteTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public int PickTimeout {
            get {
                return ((int)(this["PickTimeout"]));
            }
            set {
                this["PickTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int ReadPoseTimeout {
            get {
                return ((int)(this["ReadPoseTimeout"]));
            }
            set {
                this["ReadPoseTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int MoveTimeout {
            get {
                return ((int)(this["MoveTimeout"]));
            }
            set {
                this["MoveTimeout"] = value;
            }
        }
    }
}
